version: '3.3'

services:
  indoor-tracking:
    container_name: "api-indoor-tracking"
    build: 
      context: .
    ports:
      - 8000:8000
    environment:
      - DB_USER
      - DB_PASSWORD

networks:
  api-network:
    external: true