version: '3.3'

services:
  indoor-tracking:
    container_name: "api-indoor-tracking"
    build: 
      context: .
    ports:
      - 8000:8000
    environment:
      - DB_URL
      - DB_NAME
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_FROM
      - MAIL_PORT
      - MAIL_SERVER

networks:
  api-network:
    external: true