name: Build deploy API

on:
  push:
    branches:
      - api-deploy

env:
  IMAGE: api
#  PORT: 8080
#  REGION: us-east1
#  CPU: 1
#  MEMORY: 512Mi
#  TIMEOUT: 300
#  CONCURRENCY: 80
#  MAX_INSTANCES: 1
#  MIN_INSTANCES: 0
#  SECRET: ${{ secrets.SECRET }}

jobs:
  setup-build-publish-deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    environment: backend

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Docker configuration
      run: |-
        gcloud auth configure-docker \
        us-east1-docker.pkg.dev

    - name: Build
      run: |-
        docker build \
          --tag "us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ar-backend/${{ env.IMAGE }}:latest" \
          .

    - name: Publish
      run: |-
        docker push "us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ar-backend/${{ env.IMAGE }}:latest"

#    - name: Deploy
#      run: |
#        gcloud run deploy run-${{ env.IMAGE }} \
#        --image us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ar-dev-faas/${{ env.IMAGE }}:latest \
#        --port=$PORT \
#        --platform managed \
#        --vpc-egress=all-traffic \
#        --vpc-connector=projects/prj-4i-network-nprd/locations/us-east1/connectors/vpc-con-4i-nprod-cloudrun \
#        --project ${{ secrets.GCP_PROJECT }} \
#        --region $REGION \
#        --set-env-vars=SECRET=$SECRET \
#        --timeout=$TIMEOUT \
#        --concurrency=$CONCURRENCY \
#        --min-instances=$MIN_INSTANCES \
#        --max-instances=$MAX_INSTANCES \
#        --cpu=$CPU \
#        --memory=$MEMORY 